version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookwormdevdb
      POSTGRES_USER: devmikun
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./pgdata:/var/lib/postgresql/data
